alias k="kubectl -n test"
alias kg="kubectl -n test get"
alias kr="kubectl -n test run"
alias kgns="kubectl -n test get ns -o wide"
alias ke="kubectl -n test edit"
alias kep="kubectl -n test edit pod"
alias ked="kubectl -n test edit deploy"
alias kes="kubectl -n test edit service"
alias kenp="kubectl -n test edit networkpolicy"
alias kgp="watch -n 0.2 kubectl -n test get pods -o wide"
alias kgd="watch -n 0.2 kubectl -n test get deploy -o wide"
alias kgs="watch -n 0.2 kubectl -n test get services -o wide"
alias kgnp="watch -n 0.2 kubectl -n test get networkpolicy -o wide"
alias kd="kubectl -n test describe"
alias kdp="kubectl -n test describe pod"
alias kdd="kubectl -n test describe deploy"
alias kds="kubectl -n test describe service"
alias kdns="kubectl -n test describe ns"
alias kdnp="kubectl -n test describe networkpolicy"
alias kapp="kubectl -n test apply -f"
alias kdel="kubectl -n test delete "
alias klogs="kubectl -n test logs"

alias bo="BOSH_CLIENT=ops_manager BOSH_CLIENT_SECRET=jge89_UVPLoUmdCrrZa8dP3_TX6B9uli BOSH_CA_CERT=/var/tempest/workspaces/default/root_ca_certificate BOSH_ENVIRONMENT=21.172.1.4 bosh"
